name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get last message
        run: echo "last_message=$(git log -n 1 --pretty=format:%s)" >> $GITHUB_OUTPUT

      - name: echo last_message
        run: echo ${{ steps.last_message.outputs.last_message }}
