name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  find-what-to-deploy:
    runs-on: ubuntu-latest
    # outputs:
    #   cr_services: ${{ steps.extract-deploy-services.outputs.cr_services_to_deploy }}

    steps:
      - uses: actions/checkout@v4

      - name: Get services
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/workflows/scripts/extract-deploy-services.js');
            await script("${{ github.event.head_commit.message }}", { github, core, context });
