name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run a one-line script
        run: echo "last_message=$(git log HEAD~1..HEAD --pretty=format:%s)" >> $GITHUB_OUTPUT
