name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  find-what-to-deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      run_services: ${{ steps.get_services.outputs.run_services }}
      function_services: ${{ steps.get_services.outputs.function_services }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get_merged_commit
        run: echo "commits=$(git log HEAD~1..HEAD --oneline)" >> $GITHUB_OUTPUT

      - run: echo ${{ steps.get_merged_commit.outputs.commits }}

      # - id: get_services
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const script = require('./.github/workflows/scripts/extract-pull-requests.js');
      #       await script({ github, core, context });

  # deploy-cloud-functions:
  #   runs-on: ubuntu-latest
  #   needs: find-what-to-deploy
  #   if: needs.find-what-to-deploy.outputs.function_services != ''
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Deploy Cloud Functions
  #       run: |
  #         echo "Deploying Cloud Functions: ${{ needs.find-what-to-deploy.outputs.function_services }}"
  #
  # deploy-cloud-run:
  #   runs-on: ubuntu-latest
  #   needs: find-what-to-deploy
  #   if: needs.find-what-to-deploy.outputs.run_services != ''
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Deploy Cloud Run
  #       run: |
  #         echo "Deploying Cloud Run: ${{ needs.find-what-to-deploy.outputs.run_services }}"
