name: To production

on:
  pull_request:
    types:
      - closed

jobs:
  find-what-to-deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    if: github.event.pull_request.merged == true

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
