name: To production

on:
  pull_request:
    types:
      - closed

jobs:
  find-what-to-deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo ${{ toJson(github) }}
