name: To staging

on:
  push:
    branches: ["staging"]

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

  find-what-to-deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      run_services: ${{ steps.get_services.outputs.run_services }}
      function_services: ${{ steps.get_services.outputs.function_services }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get_commits
        run: |
          echo 'commits<<EOF' >> $GITHUB_OUTPUT
          echo "$(git log --pretty=format:%s HEAD~1..HEAD)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Get services to deploy
        uses: actions/github-script@v7
        env:
          commits: ${{ steps.get_commits.outputs.commits }}
        with:
          script: |
            const script = require('./.github/workflows/scripts/extract-pull-requests.js');
            await script(process.env.commits, { github, core, context });
