name: To staging

on:
  pull_request:
    branches: ["staging"]
    types: ["closed"]

jobs:
  if-is-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      is_pr_merge: ${{ steps.is_pr_merge.outputs.is_pr_merge }}
    steps:
      - run: echo "is_pr_merge=true" >> $GITHUB_OUTPUT

  find-what-to-deploy:
    runs-on: ubuntu-latest
    needs: if-is-merged-pr
    if: needs.if-is-merged-pr.outputs.is_pr_merge == 'true'
    permissions: read-all
    outputs:
      run_services: ${{ steps.get_services.outputs.run_services }}
      function_services: ${{ steps.get_services.outputs.function_services }}
    steps:
      - uses: actions/checkout@v4

      - name: Get services to deploy
        id: get_services
        uses: actions/github-script@v7
        env:
          pr_number: ${{ github.event.number }}
        with:
          script: |
            const script = require('./.github/workflows/scripts/extract-pull-requests.js');
            await script(process.env.pr_number, { github, core, context });

  deploy-cloud-functions:
    runs-on: ubuntu-latest
    needs: find-what-to-deploy
    if: needs.find-what-to-deploy.outputs.function_services != ''
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Cloud Functions
        run: |
          echo "Deploying Cloud Functions: ${{ needs.find-what-to-deploy.outputs.function_services }}"

  deploy-cloud-run:
    runs-on: ubuntu-latest
    needs: find-what-to-deploy
    if: needs.find-what-to-deploy.outputs.run_services != ''
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Cloud Run
        run: |
          echo "Deploying Cloud Run: ${{ needs.find-what-to-deploy.outputs.run_services }}"
